---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 繁星.
--- DateTime: 2026/4/14 22:55
---

local voucherId = ARGV[1]
local userId = ARGV[2]
local orderId = ARGV[3]

local stockKey = 'seckill:stock:' .. voucherId
local orderKey = 'seckill:order:' .. voucherId
local streamName = 'stream.orders'

if (redis.call('exists', stockKey) == 0) then
    return 1
end

if (tonumber(redis.call('get', stockKey)) <= 0) then
    return 2
end

if (redis.call('sismember', orderKey, userId) == 1) then
    return 3
end

redis.call('incrby', stockKey, -1)
redis.call('sadd', orderKey, userId)

redis.call('xadd', streamName, '*', 'userId', userId, 'voucherId', voucherId, 'orderId', orderId)

return 0
